### ISSUE TITLE
Startup script cannot be called as an executable

### ISSUE THREAD

**Issue by Quickeman** [Quickeman/DrumPi#16]
The startup script must be called as `bash Drumpi.sh` rather than just `DrumPi` or `./DrumPi`.
Should we find a way to automatically make the script an executable at build/compile time?

**Comment by murdograham** [comment]
chmod should make the file executable for any user of the repo

**Comment by stuartb-rt** [comment]
That's fixed the issue for me, can now run the program using ./DrumPi
