### ISSUE TITLE
Changing the volume is only noticeable at the extremes

### ISSUE THREAD

**Issue by stuartb-rt** [Quickeman/DrumPi#23]
Got some user feedback saying that modifying the volume only becomes noticeable at the volume extremes, and that small changes appear imperceptible. Anything we could do to fix this?

**Comment by Quickeman** [comment]
Making the volume scaling exponential would be a good start.
I'll have a go at implementing that and see if it makes the volume settings more effective.

**Comment by murdograham** [comment]
I guess a more crude method would be to increase the increment/decrement value however this reduces fine tuning ability

**Comment by stuartb-rt** [comment]
That's working much better, the volume change is much more perceptible.
