### ISSUE TITLE
Should display exit sub-mode when mode key is pressed?

### ISSUE THREAD

**Issue by stuartb-rt** [Quickeman/DrumPi#24]
Got some user feedback suggesting that the display should exit its current sub-mode and return to current mode when a mode key is pressed. For example, pressing spacebar in SetTempoMode should return the display to Sequencer Mode.

**Comment by Quickeman** [comment]
I'd agree with that.
Are there any other examples of this where that isn't already the case?

**Comment by stuartb-rt** [comment]
Pretty much any case where the state doesn't explicitly change:

Pressing the drum sound keys in SetTempoMode,
Pressing spacebar in SetTempoMode
Pressing 1-8 in SetTempoMode,
Pressing tab in SetTempoMode,
Pressing 1-8 in SetDrumBankMode when primary mode is Sequencer Mode,
Pressing tab in SetDrumBankMode when primary mode is Sequencer Mode,
Pressing spacebar in SetDrumBankMode when primary mode is Sequencer Mode,
Pressing 1-8  in SetDrumVolumeMode when primary mode is Sequencer Mode,
Pressing tab in SetDrumVolumeMode when primary mode is Sequencer Mode,
Pressing spacebar in SetDrumVolumeMode when primary mode is Sequencer Mode.
There are probably more, but you get the idea.

**Comment by Quickeman** [comment]
Ok, this should be fairly easy to do I think.

**Comment by murdograham** [comment]
Agreed, sounds good. Should be able to implement this tonight. Just to clarify - should the display mode return when pressing ANY of the keys mentioned above? Or just spacebar?

**Comment by Quickeman** [comment]
It should return when any of the keys are pressed. The sub-mode will also need to return to setting the master volume to avoid confusion I think though.

**Comment by stuartb-rt** [comment]
Agreed.

**Comment by stuartb-rt** [comment]
That fix works great, cheers Finn
