### ISSUE TITLE
test_sampleSource fails when ran on a new Raspberry Pi

### ISSUE THREAD

**Issue by stuartb-rt** [Quickeman/DrumPi#8]
The unit test "test_sampleSource.cpp" on the application branch currently fails when run on a new Raspberry Pi.

**Comment by Quickeman** [comment]
I think this might be because the system currently uses an absolute filepath system without getting the absolute filepath of where the repository's root directory is.
I'll add a system to do this and see if that helps.

**Comment by Quickeman** [comment]
@stuartb-rt Try running the tests now to see if the issue is resolved.

**Comment by stuartb-rt** [comment]
That's fixed it, the test now passes, cheers.
